[build]
  command = "npm run build:netlify"
  publish = "dist/viajero-frontend/browser"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"